theme: jekyll-theme-cayman
title: STTP API for Python
description: STTP Python API
github:
  repository_name: pyapi
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
include: 
  - html/*
plugins:
  - jemoji
